version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1
      - image: circleci/postgres:9.5.13-alpine-ram
    environment:
      # - DATABASE_URL: postgres://username:pgpassword@db:5432/mydatabase
      - NODE_ENV: 'test'
      - POSTGRES_DB: 'abletable'
      - POSTGRES_HOST: 'localhost'
      - POSTGRES_USER: 'fiona'
      - POSTGRES_PORT: 5432
    steps:
      - checkout
      - run: npm install
      - run: npm test
