version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1
      - image: circleci/postgres:9.5.13-alpine-ram
      - image: circleci/mongo:3.6.5
    environment:
      - MONGO_URL: "mongodb://localhost:27017/cavatable_menus"
      - NODE_ENV: 'test'
      - POSTGRES_DB: 'abletable'
      - POSTGRES_HOST: 'localhost'
      - POSTGRES_USER: 'fiona'
      - POSTGRES_PORT: 5432
    steps:
      - checkout
      - run: npm install
      - run: npm test
