version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1
      - image: circleci/postgres:9.5.13-alpine-ram
        environment:
          POSTGRES_DB: 'abletable'
          POSTGRES_HOST: 'localhost'
          POSTGRES_USER: 'root'
          POSTGRES_PORT: 5432
      - image: circleci/mongo:3.6.5
    environment:
      - POSTGRES_DB: 'abletable'
      - POSTGRES_HOST: 'localhost'
      - POSTGRES_USER: 'root'
      - POSTGRES_PORT: 5432
      - MONGO_URL: "mongodb://localhost:27017/cavatable_menus"
      - NODE_ENV: 'test'
    steps:
      - checkout
      - run: npm install
      - run: yum install postgres-client
      - run: psql -u root < database/postSQLSchema.sql
      - run: npm test
